comment=""

[train]
model_path = "SEDNet_{}_lr_{}_mode_{}_k{}"

gpu = "0"

# Dataset path
dataset = "data_parsenet"

# Whether to load a pretrained model or not
preload_model = True


# pre-trained model path
pretrain_model_path = "trains/SEDNet_6_lr_0.0001_mode_15_k64/ckpts/SEDNet_6_lr_0.0001_mode_15_k64_InstBest.pth"
pretrain_model_type_path = "trains/SEDNet_6_lr_0.0001_mode_15_k64/ckpts/SEDNet_6_lr_0.0001_mode_15_k64_TypeBest.pth"
pretrain_opti_path = ""


# Whether to input the normals or not
normals = False

proportion = 1.0

# number of training instance
num_train=16000 
num_val=2700
num_test=2700
num_points=10000  # default 10000
loss_weight=100

num_epochs = 200
grid_size = 20


batch_size = 6

# Optimization
optim = adamW

smooth = 0.025  # ============================= BCE smooth label, default 0.2
sche = "reduce"  # cos / reduce scheduler
embed = 128  # default 128

knn = 64  # ======================== default 64

# l2 Weight decay
weight_decay = 0.002  # default 1e-4

# dropout for Decoder network
dropout = 0.2

# Learing rate
lr = 0.0001  # 4e-4
eval_T = 2000

# Encoder dropout
encoder_drop = 0.0   # default 0.0

# Whether to schedule the learning rate or not
lr_sch = True
patience = 5
mode = 15 
